/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/paper-inactive.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    drawing_empty: THREE.Mesh
  }
  materials: {
    paper: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/paper-inactive.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.drawing_empty.geometry} material={materials.paper} />
    </group>
  )
}

useGLTF.preload('/paper-inactive.glb')
