/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/paper-active.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    drawing_S: THREE.Mesh
  }
  materials: {
    ['paper_-_S']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/paper-active.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.drawing_S.geometry} material={materials['paper_-_S']} />
    </group>
  )
}

useGLTF.preload('/paper-active.glb')
