/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/television-inactive.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TV_off_1: THREE.Mesh
    TV_off_2: THREE.Mesh
  }
  materials: {
    ['boombox_-_light']: THREE.MeshStandardMaterial
    tv: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/television-inactive.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TV_off_1.geometry} material={materials['boombox_-_light']} />
      <mesh geometry={nodes.TV_off_2.geometry} material={materials.tv} />
    </group>
  )
}

useGLTF.preload('/television-inactive.glb')
