/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/television-active.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TV_on_001: THREE.Mesh
    TV_on_001_1: THREE.Mesh
  }
  materials: {
    ['tv.002']: THREE.MeshStandardMaterial
    ['tv_screen.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/television-active.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TV_on_001.geometry} material={materials['tv.002']} />
      <mesh geometry={nodes.TV_on_001_1.geometry} material={materials['tv_screen.001']} />
    </group>
  )
}

useGLTF.preload('/television-active.glb')
