/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/astronaut.glb -t
*/

import * as THREE from "three";
//@ts-ignore
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Astronaut_mesh: THREE.Mesh;
  };
  materials: {
    Astronaut_mat: THREE.MeshStandardMaterial;
  };
  //@ts-ignore
  animations: GLTFAction[];
};

//@ts-ignore
export function AstronautModel(props: JSX.IntrinsicElements["group"]) {
  //@ts-ignore
  const { nodes, materials } = useGLTF("/models/astronaut.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Astronaut_mesh.geometry}
        material={materials.Astronaut_mat}
      />
    </group>
  );
}

useGLTF.preload("/models/astronaut.glb");
