/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/torii.glb -t
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Node-Mesh']: THREE.Mesh
    ['Node-Mesh_1']: THREE.Mesh
  }
  materials: {
    mat23: THREE.MeshStandardMaterial
    mat14: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Torii(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/torii.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat14} />
    </group>
  )
}

useGLTF.preload('/models/torii.glb')
