/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/book-inactive.glb -t
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    book_closed_1: THREE.Mesh;
    book_closed_2: THREE.Mesh;
  };
  materials: {
    ["white.009"]: THREE.MeshStandardMaterial;
    ["blue.003"]: THREE.MeshStandardMaterial;
  };
  // @ts-expect-error Cannot find name
  animations: GLTFAction[];
};

export function BookInactiveModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/book-inactive.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.book_closed_1.geometry}
        material={materials["white.009"]}
      />
      <mesh
        geometry={nodes.book_closed_2.geometry}
        material={materials["blue.003"]}
      />
    </group>
  );
}

useGLTF.preload("/models/book-inactive.glb");
