/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/book-active.glb -t
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    opened_book001: THREE.Mesh;
    opened_book001_1: THREE.Mesh;
  };
  materials: {
    ["blue.001"]: THREE.MeshStandardMaterial;
    ["book_-_white.001"]: THREE.MeshStandardMaterial;
  };
  // @ts-expect-error Cannot find name
  animations: GLTFAction[];
};

export function BookActiveModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/book-active.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.opened_book001.geometry}
        material={materials["blue.001"]}
      />
      <mesh
        geometry={nodes.opened_book001_1.geometry}
        material={materials["book_-_white.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/book-active.glb");
