/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ds-active.glb -t
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    NDS_open_1: THREE.Mesh;
    NDS_open_2: THREE.Mesh;
  };
  materials: {
    ["DS_-_green"]: THREE.MeshStandardMaterial;
    ["DS_-_screen"]: THREE.MeshStandardMaterial;
  };
  // @ts-expect-error Cannot find name
  animations: GLTFAction[];
};

export function DSActiveModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/ds-active.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.NDS_open_1.geometry}
          material={materials["DS_-_green"]}
        />
        <mesh
          geometry={nodes.NDS_open_2.geometry}
          material={materials["DS_-_screen"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ds-active.glb");
