/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ds-inactive.glb -t
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    NDS_closed001: THREE.Mesh;
    NDS_closed001_1: THREE.Mesh;
  };
  materials: {
    ["DS_-_green.002"]: THREE.MeshStandardMaterial;
    ["DS_-_screen.002"]: THREE.MeshStandardMaterial;
  };
  // @ts-expect-error Cannot find name
  animations: GLTFAction[];
};

export function DSInactiveModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/ds-inactive.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.NDS_closed001.geometry}
        material={materials["DS_-_green.002"]}
      />
      <mesh
        geometry={nodes.NDS_closed001_1.geometry}
        material={materials["DS_-_screen.002"]}
      />
    </group>
  );
}

useGLTF.preload("/models/ds-inactive.glb");
