/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/game-boy.glb -t
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
    ["Node-Mesh_2"]: THREE.Mesh;
    ["Node-Mesh_3"]: THREE.Mesh;
    ["Node-Mesh_4"]: THREE.Mesh;
    ["Node-Mesh_5"]: THREE.Mesh;
  };
  materials: {
    mat21: THREE.MeshStandardMaterial;
    mat7: THREE.MeshStandardMaterial;
    mat23: THREE.MeshStandardMaterial;
    mat15: THREE.MeshStandardMaterial;
    mat12: THREE.MeshStandardMaterial;
    mat17: THREE.MeshStandardMaterial;
  };
  // @ts-expect-error Cannot find name
  animations: GLTFAction[];
};

export function GameboyModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/gameboy.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat21} />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat7}
      />
      <mesh
        geometry={nodes["Node-Mesh_2"].geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes["Node-Mesh_3"].geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes["Node-Mesh_4"].geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes["Node-Mesh_5"].geometry}
        material={materials.mat17}
      />
    </group>
  );
}

useGLTF.preload("/models/gameboy.glb");
