/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/paper-inactive.glb -t 
*/

import * as THREE from 'three'
import { JSX } from "react"
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    drawing_empty: THREE.Mesh
  }
  materials: {
    paper: THREE.MeshStandardMaterial
  }
  // @ts-expect-error Cannot find name
  animations: GLTFAction[]
}

export function PaperInactiveModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/paper-inactive.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.drawing_empty.geometry} material={materials.paper} />
    </group>
  )
}

useGLTF.preload('/models/paper-inactive.glb')
