/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/phone-active.glb -t
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    phone_close001: THREE.Mesh;
    phone_close001_1: THREE.Mesh;
  };
  materials: {
    ["phone_-_red.002"]: THREE.MeshStandardMaterial;
    ["phone_-_red.003"]: THREE.MeshStandardMaterial;
  };
  // @ts-expect-error Cannot find name
  animations: GLTFAction[];
};

export function PhoneActiveModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/phone-active.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.phone_close001.geometry}
        material={materials["phone_-_red.002"]}
      />
      <mesh
        geometry={nodes.phone_close001_1.geometry}
        material={materials["phone_-_red.003"]}
      />
    </group>
  );
}

useGLTF.preload("/models/phone-active.glb");
