/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/room.glb -t
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    desk: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    tv_stand: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube013_2: THREE.Mesh;
    Cube013_3: THREE.Mesh;
    Cube013_4: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder005_1: THREE.Mesh;
    Cylinder005_2: THREE.Mesh;
    Cylinder005_3: THREE.Mesh;
    Cylinder005_4: THREE.Mesh;
    Cylinder005_5: THREE.Mesh;
    Cylinder005_6: THREE.Mesh;
    Cylinder005_7: THREE.Mesh;
    Sphere: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    Cube011_2: THREE.Mesh;
    Cube011_3: THREE.Mesh;
    Cube011_4: THREE.Mesh;
    Cube011_5: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube012_1: THREE.Mesh;
    Cube012_2: THREE.Mesh;
    Cube012_3: THREE.Mesh;
    Cube012_4: THREE.Mesh;
    Cube012_5: THREE.Mesh;
    bedside_drawer: THREE.Mesh;
    cardboard_box: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Cube018_2: THREE.Mesh;
    bookshelf: THREE.Mesh;
    shelf: THREE.Mesh;
    shelf_2: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube031_1: THREE.Mesh;
    Cube031_2: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Cylinder012_1: THREE.Mesh;
    Cylinder012_2: THREE.Mesh;
    Cylinder012_3: THREE.Mesh;
    Cube045: THREE.Mesh;
    Cube045_1: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube004_1: THREE.Mesh;
    Cube004_2: THREE.Mesh;
    Cube004_3: THREE.Mesh;
    Cube004_4: THREE.Mesh;
    Cube004_5: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    drawing_empty: THREE.Mesh;
    explore_2_poster: THREE.Mesh;
    explore_1_poster: THREE.Mesh;
    nintendo_poster: THREE.Mesh;
    among_us_poster: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    drawing_S: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube019_1: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube038_1: THREE.Mesh;
  };
  materials: {
    ["room - blue"]: THREE.MeshStandardMaterial;
    ["room - gorund"]: THREE.MeshStandardMaterial;
    ["room - wood"]: THREE.MeshStandardMaterial;
    ["Desk - brown"]: THREE.MeshStandardMaterial;
    ["boombox - light"]: THREE.MeshStandardMaterial;
    tv: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    ["lamp - silver"]: THREE.MeshStandardMaterial;
    ["lamp - orange"]: THREE.MeshStandardMaterial;
    ["lamp - yellow light"]: THREE.MeshStandardMaterial;
    ["lamp - dark "]: THREE.MeshStandardMaterial;
    ["lamp - red"]: THREE.MeshStandardMaterial;
    ["DS - green"]: THREE.MeshStandardMaterial;
    ["DS - screen"]: THREE.MeshStandardMaterial;
    ["boombox - silver"]: THREE.MeshStandardMaterial;
    ["boombox - orange"]: THREE.MeshStandardMaterial;
    ["boombox - blue"]: THREE.MeshStandardMaterial;
    ["boombox - black"]: THREE.MeshStandardMaterial;
    ["boombox - red"]: THREE.MeshStandardMaterial;
    ["boombox - green"]: THREE.MeshStandardMaterial;
    ["boombox dark"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    ["white.002"]: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    ["white.001"]: THREE.MeshStandardMaterial;
    green: THREE.MeshStandardMaterial;
    ["red.005"]: THREE.MeshStandardMaterial;
    ["white.005"]: THREE.MeshStandardMaterial;
    ["white.003"]: THREE.MeshStandardMaterial;
    ["blue.001"]: THREE.MeshStandardMaterial;
    ["white.004"]: THREE.MeshStandardMaterial;
    ["green.003"]: THREE.MeshStandardMaterial;
    ["bed - brown"]: THREE.MeshStandardMaterial;
    ["box texture.002"]: THREE.MeshStandardMaterial;
    ["bed - blue"]: THREE.MeshStandardMaterial;
    ["bed - yellow"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["shelf 1 - brown"]: THREE.MeshStandardMaterial;
    ["shelf 2 - brown"]: THREE.MeshStandardMaterial;
    ["door - white"]: THREE.MeshStandardMaterial;
    ["door - gold"]: THREE.MeshStandardMaterial;
    ["door- green"]: THREE.MeshStandardMaterial;
    ["clock - dark"]: THREE.MeshStandardMaterial;
    ["clock - yellow"]: THREE.MeshStandardMaterial;
    ["clock - orange"]: THREE.MeshStandardMaterial;
    ["clock - red"]: THREE.MeshStandardMaterial;
    ["Chair-blue"]: THREE.MeshStandardMaterial;
    ["Chair - black"]: THREE.MeshStandardMaterial;
    ["white.008"]: THREE.MeshStandardMaterial;
    ["blue.002"]: THREE.MeshStandardMaterial;
    ["red.006"]: THREE.MeshStandardMaterial;
    ["white.006"]: THREE.MeshStandardMaterial;
    ["white.007"]: THREE.MeshStandardMaterial;
    ["green.004"]: THREE.MeshStandardMaterial;
    ["phone - red.002"]: THREE.MeshStandardMaterial;
    ["phone - red.003"]: THREE.MeshStandardMaterial;
    paper: THREE.MeshStandardMaterial;
    ["explorer poster"]: THREE.MeshStandardMaterial;
    ["explorer poster.001"]: THREE.MeshStandardMaterial;
    ["explorer poster.002"]: THREE.MeshStandardMaterial;
    ["explorer poster.003"]: THREE.MeshStandardMaterial;
    ["white.009"]: THREE.MeshStandardMaterial;
    ["blue.003"]: THREE.MeshStandardMaterial;
    ["white.010"]: THREE.MeshStandardMaterial;
    ["green.007"]: THREE.MeshStandardMaterial;
    ["paper - S"]: THREE.MeshStandardMaterial;
    ["DS - green.001"]: THREE.MeshStandardMaterial;
    ["DS - screen.001"]: THREE.MeshStandardMaterial;
    ["book - white"]: THREE.MeshStandardMaterial;
    ["phone - red.001"]: THREE.MeshStandardMaterial;
    ["phone - red"]: THREE.MeshStandardMaterial;
  };
};

interface RoomModelProps {
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number | [number, number, number];
}

export function RoomModel({
  position = [0, 0, 0],
  rotation = [0, 0, 0],
  scale = 1,
}: RoomModelProps) {
  const { nodes, materials } = useGLTF(
    "/models/room.glb",
  ) as unknown as GLTFResult;
  return (
    <group position={position} rotation={rotation} scale={scale} dispose={null}>
      <group position={[202.705, 64.574, 0]} scale={[84.506, 23.866, 130.927]}>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["room - blue"]}
        />
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["room - gorund"]}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["room - wood"]}
        />
      </group>
      <mesh
        geometry={nodes.desk.geometry}
        material={materials["Desk - brown"]}
        position={[249.969, 68.939, -88.57]}
        scale={[-23.767, -0.739, -16.517]}
      />
      <group
        position={[149.362, 61.255, -84.607]}
        rotation={[0, 0.534, 0]}
        scale={[1.191, 0.912, 0.819]}
      >
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials["boombox - light"]}
        />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.tv} />
      </group>
      <mesh
        geometry={nodes.tv_stand.geometry}
        material={materials.brown}
        position={[147.112, 60.541, -88.416]}
        rotation={[0, 0.534, 0]}
        scale={[13.814, 0.889, 8.546]}
      />
      <group position={[259.672, 78.584, -91.256]}>
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials["lamp - silver"]}
        />
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials["lamp - orange"]}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials["lamp - yellow light"]}
        />
        <mesh
          geometry={nodes.Cube013_3.geometry}
          material={materials["lamp - dark "]}
        />
        <mesh
          geometry={nodes.Cube013_4.geometry}
          material={materials["lamp - red"]}
        />
      </group>
      <group
        position={[258.963, 71.697, -2.481]}
        rotation={[-2.033, -1.515, -2.032]}
        scale={[1.431, 0.299, 0.077]}
      >
        <mesh
          geometry={nodes.Cube022.geometry}
          material={materials["DS - green"]}
        />
        <mesh
          geometry={nodes.Cube022_1.geometry}
          material={materials["DS - screen"]}
        />
      </group>
      <group
        position={[189.798, 79.412, -92.746]}
        rotation={[0.006, 0.066, 0]}
        scale={[1.278, 1.346, 1]}
      >
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials["boombox - silver"]}
        />
        <mesh
          geometry={nodes.Cylinder005_1.geometry}
          material={materials["boombox - orange"]}
        />
        <mesh
          geometry={nodes.Cylinder005_2.geometry}
          material={materials["boombox - blue"]}
        />
        <mesh
          geometry={nodes.Cylinder005_3.geometry}
          material={materials["boombox - light"]}
        />
        <mesh
          geometry={nodes.Cylinder005_4.geometry}
          material={materials["boombox - black"]}
        />
        <mesh
          geometry={nodes.Cylinder005_5.geometry}
          material={materials["boombox - red"]}
        />
        <mesh
          geometry={nodes.Cylinder005_6.geometry}
          material={materials["boombox - green"]}
        />
        <mesh
          geometry={nodes.Cylinder005_7.geometry}
          material={materials["boombox dark"]}
        />
      </group>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
        position={[190.114, 53.077, 43.744]}
      />
      <group
        position={[239.345, 77.279, -98.471]}
        rotation={[1.101, -1.531, 1.106]}
        scale={1.432}
      >
        <mesh geometry={nodes.Cube011.geometry} material={materials.red} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.white} />
        <mesh
          geometry={nodes.Cube011_2.geometry}
          material={materials["white.002"]}
        />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials.blue} />
        <mesh
          geometry={nodes.Cube011_4.geometry}
          material={materials["white.001"]}
        />
        <mesh geometry={nodes.Cube011_5.geometry} material={materials.green} />
      </group>
      <group
        position={[244.484, 69.374, -80.296]}
        rotation={[Math.PI, -1.331, Math.PI]}
        scale={1.378}
      >
        <mesh
          geometry={nodes.Cube012.geometry}
          material={materials["red.005"]}
        />
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={materials["white.005"]}
        />
        <mesh
          geometry={nodes.Cube012_2.geometry}
          material={materials["white.003"]}
        />
        <mesh
          geometry={nodes.Cube012_3.geometry}
          material={materials["blue.001"]}
        />
        <mesh
          geometry={nodes.Cube012_4.geometry}
          material={materials["white.004"]}
        />
        <mesh
          geometry={nodes.Cube012_5.geometry}
          material={materials["green.003"]}
        />
      </group>
      <mesh
        geometry={nodes.bedside_drawer.geometry}
        material={materials["bed - brown"]}
        position={[203.274, 58.374, 100.669]}
        rotation={[0, 1.517, 0]}
        scale={2.289}
      />
      <mesh
        geometry={nodes.cardboard_box.geometry}
        material={materials["box texture.002"]}
        position={[152.87, 58.594, -5.199]}
        scale={2.881}
      />
      <group
        position={[161.158, 68.896, 102.343]}
        rotation={[0, -0.003, 0]}
        scale={[3.002, 21.084, 1.818]}
      >
        <mesh
          geometry={nodes.Cube018.geometry}
          material={materials["bed - blue"]}
        />
        <mesh
          geometry={nodes.Cube018_1.geometry}
          material={materials["bed - brown"]}
        />
        <mesh
          geometry={nodes.Cube018_2.geometry}
          material={materials["bed - yellow"]}
        />
      </group>
      <mesh
        geometry={nodes.bookshelf.geometry}
        material={materials["Material.002"]}
        position={[251.798, 74.457, 87.404]}
        rotation={[3.139, -0.78, 3.138]}
        scale={[19.621, 0.606, 6.629]}
      />
      <mesh
        geometry={nodes.shelf.geometry}
        material={materials["shelf 1 - brown"]}
        position={[195.365, 62.84, -97.124]}
        scale={[18.19, 11.661, 6.47]}
      />
      <mesh
        geometry={nodes.shelf_2.geometry}
        material={materials["shelf 2 - brown"]}
        position={[263.774, 69.385, -4.947]}
        rotation={[0, -1.484, 0]}
        scale={[9.341, 18.031, 6.453]}
      />
      <group
        position={[125.798, 77.673, -26.555]}
        scale={[3.901, 35.96, 18.796]}
      >
        <mesh
          geometry={nodes.Cube031.geometry}
          material={materials["door - white"]}
        />
        <mesh
          geometry={nodes.Cube031_1.geometry}
          material={materials["door - gold"]}
        />
        <mesh
          geometry={nodes.Cube031_2.geometry}
          material={materials["door- green"]}
        />
      </group>
      <group position={[203.848, 64.441, 103.577]} rotation={[0, 1.526, 0]}>
        <mesh
          geometry={nodes.Cylinder012.geometry}
          material={materials["clock - dark"]}
        />
        <mesh
          geometry={nodes.Cylinder012_1.geometry}
          material={materials["clock - yellow"]}
        />
        <mesh
          geometry={nodes.Cylinder012_2.geometry}
          material={materials["clock - orange"]}
        />
        <mesh
          geometry={nodes.Cylinder012_3.geometry}
          material={materials["clock - red"]}
        />
      </group>
      <group
        position={[257.589, 57.679, -61.022]}
        rotation={[-1.555, 0, 0]}
        scale={[7.199, 5.95, 1.194]}
      >
        <mesh
          geometry={nodes.Cube045.geometry}
          material={materials["Chair-blue"]}
        />
        <mesh
          geometry={nodes.Cube045_1.geometry}
          material={materials["Chair - black"]}
        />
      </group>
      <group
        position={[258.606, 75.084, 79.066]}
        rotation={[3.105, 0.216, -3.129]}
        scale={1.432}
      >
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials["white.008"]}
        />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials["blue.002"]}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials["red.006"]}
        />
        <mesh
          geometry={nodes.Cube004_3.geometry}
          material={materials["white.006"]}
        />
        <mesh
          geometry={nodes.Cube004_4.geometry}
          material={materials["white.007"]}
        />
        <mesh
          geometry={nodes.Cube004_5.geometry}
          material={materials["green.004"]}
        />
      </group>
      <group
        position={[197.465, 65.561, 99.416]}
        rotation={[Math.PI, -0.048, Math.PI]}
        scale={[2.867, 0.825, 5.017]}
      >
        <mesh
          geometry={nodes.Cube016.geometry}
          material={materials["phone - red.002"]}
        />
        <mesh
          geometry={nodes.Cube016_1.geometry}
          material={materials["phone - red.003"]}
        />
      </group>
      <mesh
        geometry={nodes.drawing_empty.geometry}
        material={materials.paper}
        position={[245.496, 69.788, -83.391]}
        scale={[4.201, 5.855, 6.102]}
      />
      <mesh
        geometry={nodes.explore_2_poster.geometry}
        material={materials["explorer poster"]}
        position={[279.194, 91.205, -21.427]}
        rotation={[1.596, 0.006, Math.PI / 2]}
        scale={[12.156, 10.753, 17.759]}
      />
      <mesh
        geometry={nodes.explore_1_poster.geometry}
        material={materials["explorer poster.001"]}
        position={[279.194, 91.919, -50.282]}
        rotation={[1.596, 0.006, Math.PI / 2]}
        scale={[12.156, 10.753, 17.759]}
      />
      <mesh
        geometry={nodes.nintendo_poster.geometry}
        material={materials["explorer poster.002"]}
        position={[126.07, 93.309, 86.532]}
        rotation={[1.546, -0.004, -1.654]}
        scale={[12.156, 10.753, 17.759]}
      />
      <mesh
        geometry={nodes.among_us_poster.geometry}
        material={materials["explorer poster.003"]}
        position={[125.985, 85.879, 59.776]}
        rotation={[1.546, -0.004, -1.654]}
        scale={[8.727, 7.307, 12.068]}
      />
      <group
        position={[251.441, 61.471, 77.99]}
        rotation={[-1.574, 0.04, -3.077]}
        scale={1.432}
      >
        <mesh
          geometry={nodes.Cube021.geometry}
          material={materials["white.009"]}
        />
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={materials["blue.003"]}
        />
      </group>
      <group
        position={[208.816, 66.71, 92.77]}
        rotation={[1.572, 0.083, -0.564]}
        scale={1.432}
      >
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials["white.010"]}
        />
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={materials["green.007"]}
        />
      </group>
      <mesh
        geometry={nodes.drawing_S.geometry}
        material={materials["paper - S"]}
        position={[245.388, 69.788, -83.391]}
        scale={[4.201, 5.855, 6.102]}
      />
      <group
        position={[259.19, 71.687, -2.431]}
        rotation={[-2.525, -1.484, -2.525]}
        scale={[1.431, 0.299, 0.077]}
      >
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials["DS - green.001"]}
        />
        <mesh
          geometry={nodes.Cube019_1.geometry}
          material={materials["DS - screen.001"]}
        />
      </group>
      <group
        position={[252.32, 65.577, 80.653]}
        rotation={[0, -0.294, 0]}
        scale={[3.99, 0.549, 4.329]}
      >
        <mesh geometry={nodes.Cube017.geometry} material={materials.blue} />
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials["book - white"]}
        />
      </group>
      <group
        position={[197.454, 65.472, 97.749]}
        rotation={[-Math.PI, 0.36, -Math.PI]}
        scale={[2.867, 0.825, 5.017]}
      >
        <mesh
          geometry={nodes.Cube038.geometry}
          material={materials["phone - red.001"]}
        />
        <mesh
          geometry={nodes.Cube038_1.geometry}
          material={materials["phone - red"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/room.glb");
