/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/room.glb -t
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    desk: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    tv_stand: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube013_2: THREE.Mesh;
    Cube013_3: THREE.Mesh;
    Cube013_4: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder005_1: THREE.Mesh;
    Cylinder005_2: THREE.Mesh;
    Cylinder005_3: THREE.Mesh;
    Cylinder005_4: THREE.Mesh;
    Cylinder005_5: THREE.Mesh;
    Cylinder005_6: THREE.Mesh;
    Cylinder005_7: THREE.Mesh;
    Sphere: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    Cube011_2: THREE.Mesh;
    Cube011_3: THREE.Mesh;
    Cube011_4: THREE.Mesh;
    Cube011_5: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube012_1: THREE.Mesh;
    Cube012_2: THREE.Mesh;
    Cube012_3: THREE.Mesh;
    Cube012_4: THREE.Mesh;
    Cube012_5: THREE.Mesh;
    bedside_drawer: THREE.Mesh;
    cardboard_box: THREE.Mesh;
    bookshelf: THREE.Mesh;
    shelf: THREE.Mesh;
    shelf_2: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube031_1: THREE.Mesh;
    Cube031_2: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Cylinder012_1: THREE.Mesh;
    Cylinder012_2: THREE.Mesh;
    Cylinder012_3: THREE.Mesh;
    Cube045: THREE.Mesh;
    Cube045_1: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube004_1: THREE.Mesh;
    Cube004_2: THREE.Mesh;
    Cube004_3: THREE.Mesh;
    Cube004_4: THREE.Mesh;
    Cube004_5: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    drawing_empty: THREE.Mesh;
    explore_2_poster: THREE.Mesh;
    explore_1_poster: THREE.Mesh;
    nintendo_poster: THREE.Mesh;
    among_us_poster: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    drawing_S: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube019_1: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube038_1: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube001_2: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
  };
  materials: {
    ["room - blue"]: THREE.MeshStandardMaterial;
    ["room - gorund"]: THREE.MeshStandardMaterial;
    ["room - wood"]: THREE.MeshStandardMaterial;
    ["Desk - brown"]: THREE.MeshStandardMaterial;
    ["boombox - light"]: THREE.MeshStandardMaterial;
    tv: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    ["lamp - silver"]: THREE.MeshStandardMaterial;
    ["lamp - orange"]: THREE.MeshStandardMaterial;
    ["lamp - yellow light"]: THREE.MeshStandardMaterial;
    ["lamp - dark "]: THREE.MeshStandardMaterial;
    ["lamp - red"]: THREE.MeshStandardMaterial;
    ["DS - green"]: THREE.MeshStandardMaterial;
    ["DS - screen"]: THREE.MeshStandardMaterial;
    ["boombox - silver"]: THREE.MeshStandardMaterial;
    ["boombox - orange"]: THREE.MeshStandardMaterial;
    ["boombox - blue"]: THREE.MeshStandardMaterial;
    ["boombox - black"]: THREE.MeshStandardMaterial;
    ["boombox - red"]: THREE.MeshStandardMaterial;
    ["boombox - green"]: THREE.MeshStandardMaterial;
    ["boombox dark"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    red: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    ["white.002"]: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    ["white.001"]: THREE.MeshStandardMaterial;
    green: THREE.MeshStandardMaterial;
    ["red.005"]: THREE.MeshStandardMaterial;
    ["white.005"]: THREE.MeshStandardMaterial;
    ["white.003"]: THREE.MeshStandardMaterial;
    ["blue.001"]: THREE.MeshStandardMaterial;
    ["white.004"]: THREE.MeshStandardMaterial;
    ["green.003"]: THREE.MeshStandardMaterial;
    ["bed - brown"]: THREE.MeshStandardMaterial;
    ["box texture.002"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["shelf 1 - brown"]: THREE.MeshStandardMaterial;
    ["shelf 2 - brown"]: THREE.MeshStandardMaterial;
    ["door - white"]: THREE.MeshStandardMaterial;
    ["door - gold"]: THREE.MeshStandardMaterial;
    ["door- green"]: THREE.MeshStandardMaterial;
    ["clock - dark"]: THREE.MeshStandardMaterial;
    ["clock - yellow"]: THREE.MeshStandardMaterial;
    ["clock - orange"]: THREE.MeshStandardMaterial;
    ["clock - red"]: THREE.MeshStandardMaterial;
    ["Chair-blue"]: THREE.MeshStandardMaterial;
    ["Chair - black"]: THREE.MeshStandardMaterial;
    ["white.008"]: THREE.MeshStandardMaterial;
    ["blue.002"]: THREE.MeshStandardMaterial;
    ["red.006"]: THREE.MeshStandardMaterial;
    ["white.006"]: THREE.MeshStandardMaterial;
    ["white.007"]: THREE.MeshStandardMaterial;
    ["green.004"]: THREE.MeshStandardMaterial;
    ["phone - red.002"]: THREE.MeshStandardMaterial;
    ["phone - red.003"]: THREE.MeshStandardMaterial;
    paper: THREE.MeshStandardMaterial;
    ["explorer poster"]: THREE.MeshStandardMaterial;
    ["explorer poster.001"]: THREE.MeshStandardMaterial;
    ["explorer poster.002"]: THREE.MeshStandardMaterial;
    ["explorer poster.003"]: THREE.MeshStandardMaterial;
    ["white.009"]: THREE.MeshStandardMaterial;
    ["blue.003"]: THREE.MeshStandardMaterial;
    ["white.010"]: THREE.MeshStandardMaterial;
    ["green.007"]: THREE.MeshStandardMaterial;
    ["paper - S"]: THREE.MeshStandardMaterial;
    ["DS - green.001"]: THREE.MeshStandardMaterial;
    ["DS - screen.001"]: THREE.MeshStandardMaterial;
    ["book - white"]: THREE.MeshStandardMaterial;
    ["phone - red.001"]: THREE.MeshStandardMaterial;
    ["phone - red"]: THREE.MeshStandardMaterial;
    ["bed - blue.001"]: THREE.MeshStandardMaterial;
    ["bed - brown.001"]: THREE.MeshStandardMaterial;
    ["bed - yellow.001"]: THREE.MeshStandardMaterial;
    ["tv.001"]: THREE.MeshStandardMaterial;
    ["tv screen"]: THREE.MeshStandardMaterial;
  };
};

interface RoomModelProps {
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number | [number, number, number];
}

export function RoomModel({
  position = [0, 0, 0],
  rotation = [0, 0, 0],
  scale = 1,
}: RoomModelProps) {
  const { nodes, materials } = useGLTF(
    "/models/room.glb",
  ) as unknown as GLTFResult;
  return (
    <group position={position} rotation={rotation} scale={scale} dispose={null}>
      <mesh
        geometry={nodes.desk.geometry}
        material={materials["Desk - brown"]}
      />
      <mesh geometry={nodes.tv_stand.geometry} material={materials.brown} />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.bedside_drawer.geometry}
        material={materials["bed - brown"]}
      />
      <mesh
        geometry={nodes.cardboard_box.geometry}
        material={materials["box texture.002"]}
      />
      <mesh
        geometry={nodes.bookshelf.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.shelf.geometry}
        material={materials["shelf 1 - brown"]}
      />
      <mesh
        geometry={nodes.shelf_2.geometry}
        material={materials["shelf 2 - brown"]}
      />
      {/* <mesh
        geometry={nodes.drawing_empty.geometry}
        material={materials.paper}
      /> */}
      <mesh
        geometry={nodes.explore_2_poster.geometry}
        material={materials["explorer poster"]}
      />
      <mesh
        geometry={nodes.explore_1_poster.geometry}
        material={materials["explorer poster.001"]}
      />
      <mesh
        geometry={nodes.nintendo_poster.geometry}
        material={materials["explorer poster.002"]}
      />
      <mesh
        geometry={nodes.among_us_poster.geometry}
        material={materials["explorer poster.003"]}
      />
      {/* <mesh
        geometry={nodes.drawing_S.geometry}
        material={materials["paper - S"]}
        position={[-2.049, -0.427, -0.563]}
      /> */}
      {/* <group position={[-2.049, -0.427, -0.563]}>
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials["DS - green.001"]}
        />
        <mesh
          geometry={nodes.Cube019_1.geometry}
          material={materials["DS - screen.001"]}
        />
      </group> */}
      {/* <group position={[-2.049, -0.427, -0.563]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials.blue} />
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials["book - white"]}
        />
      </group> */}
      {/* <group position={[0, -0.095, 0]}>
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials["tv.001"]}
        />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials["tv screen"]}
        />
      </group> */}
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["room - blue"]}
      />
      <mesh
        geometry={nodes.Cube_1.geometry}
        material={materials["room - gorund"]}
      />
      <mesh
        geometry={nodes.Cube_2.geometry}
        material={materials["room - wood"]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials["boombox - light"]}
      />
      <mesh geometry={nodes.Cube009_1.geometry} material={materials.tv} />
      {/* <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["lamp - silver"]}
      />
      <mesh
        geometry={nodes.Cube013_1.geometry}
        material={materials["lamp - orange"]}
      />
      <mesh
        geometry={nodes.Cube013_2.geometry}
        material={materials["lamp - yellow light"]}
      />
      <mesh
        geometry={nodes.Cube013_3.geometry}
        material={materials["lamp - dark "]}
      />
      <mesh
        geometry={nodes.Cube013_4.geometry}
        material={materials["lamp - red"]}
      /> */}
      {/* <mesh
        geometry={nodes.Cube022.geometry}
        material={materials["DS - green"]}
      />
      <mesh
        geometry={nodes.Cube022_1.geometry}
        material={materials["DS - screen"]}
      /> */}
      {/* <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["boombox - silver"]}
      />
      <mesh
        geometry={nodes.Cylinder005_1.geometry}
        material={materials["boombox - orange"]}
      />
      <mesh
        geometry={nodes.Cylinder005_2.geometry}
        material={materials["boombox - blue"]}
      />
      <mesh
        geometry={nodes.Cylinder005_3.geometry}
        material={materials["boombox - light"]}
      />
      <mesh
        geometry={nodes.Cylinder005_4.geometry}
        material={materials["boombox - black"]}
      />
      <mesh
        geometry={nodes.Cylinder005_5.geometry}
        material={materials["boombox - red"]}
      />
      <mesh
        geometry={nodes.Cylinder005_6.geometry}
        material={materials["boombox - green"]}
      />
      <mesh
        geometry={nodes.Cylinder005_7.geometry}
        material={materials["boombox dark"]}
      /> */}
      <mesh geometry={nodes.Cube011.geometry} material={materials.red} />
      <mesh geometry={nodes.Cube011_1.geometry} material={materials.white} />
      <mesh
        geometry={nodes.Cube011_2.geometry}
        material={materials["white.002"]}
      />
      <mesh geometry={nodes.Cube011_3.geometry} material={materials.blue} />
      <mesh
        geometry={nodes.Cube011_4.geometry}
        material={materials["white.001"]}
      />
      <mesh geometry={nodes.Cube011_5.geometry} material={materials.green} />
      <mesh geometry={nodes.Cube012.geometry} material={materials["red.005"]} />
      <mesh
        geometry={nodes.Cube012_1.geometry}
        material={materials["white.005"]}
      />
      <mesh
        geometry={nodes.Cube012_2.geometry}
        material={materials["white.003"]}
      />
      <mesh
        geometry={nodes.Cube012_3.geometry}
        material={materials["blue.001"]}
      />
      <mesh
        geometry={nodes.Cube012_4.geometry}
        material={materials["white.004"]}
      />
      <mesh
        geometry={nodes.Cube012_5.geometry}
        material={materials["green.003"]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials["door - white"]}
      />
      <mesh
        geometry={nodes.Cube031_1.geometry}
        material={materials["door - gold"]}
      />
      <mesh
        geometry={nodes.Cube031_2.geometry}
        material={materials["door- green"]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials["clock - dark"]}
      />
      <mesh
        geometry={nodes.Cylinder012_1.geometry}
        material={materials["clock - yellow"]}
      />
      <mesh
        geometry={nodes.Cylinder012_2.geometry}
        material={materials["clock - orange"]}
      />
      <mesh
        geometry={nodes.Cylinder012_3.geometry}
        material={materials["clock - red"]}
      />
      <mesh
        geometry={nodes.Cube045.geometry}
        material={materials["Chair-blue"]}
      />
      <mesh
        geometry={nodes.Cube045_1.geometry}
        material={materials["Chair - black"]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["white.008"]}
      />
      <mesh
        geometry={nodes.Cube004_1.geometry}
        material={materials["blue.002"]}
      />
      <mesh
        geometry={nodes.Cube004_2.geometry}
        material={materials["red.006"]}
      />
      <mesh
        geometry={nodes.Cube004_3.geometry}
        material={materials["white.006"]}
      />
      <mesh
        geometry={nodes.Cube004_4.geometry}
        material={materials["white.007"]}
      />
      <mesh
        geometry={nodes.Cube004_5.geometry}
        material={materials["green.004"]}
      />
      {/* <mesh
        geometry={nodes.Cube021.geometry}
        material={materials["white.009"]}
      />
      <mesh
        geometry={nodes.Cube021_1.geometry}
        material={materials["blue.003"]}
      /> */}
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials["white.010"]}
      />
      <mesh
        geometry={nodes.Cube023_1.geometry}
        material={materials["green.007"]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["bed - blue.001"]}
      />
      <mesh
        geometry={nodes.Cube001_1.geometry}
        material={materials["bed - brown.001"]}
      />
      <mesh
        geometry={nodes.Cube001_2.geometry}
        material={materials["bed - yellow.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/room.glb");
