on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          backend_deploy_url: ${{ secrets.BACKEND_DEPLOY_HOOK_URL }}
          frontend_deploy_url: ${{ secrets.FRONTEND_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploying backend..."
          curl -s "$backend_deploy_url"
          echo "Deploying frontend..."
          curl -s "$frontend_deploy_url"
