on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          backend_deploy_url: ${{ secrets.BACKEND_DEPLOY_HOOK_URL }}
          frontend_deploy_url: ${{ secrets.FRONTEND_DEPLOY_HOOK_URL }}
        run: |
          curl "$backend_deploy_url"
          curl "$frontend_deploy_url"
